apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-testing-2
  annotations:
    github.com/project-slug: Chris-Testing-Company/backstage-testing
    backstage.io/techdocs-ref: dir:.
    jira/project-key: AWN
spec:
  type: other
  lifecycle: unknown
  owner: site-reliability-engineering
