apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: catalog-info-generator-testing-2
  title: Catalog Info Generator Testing 2
  description: Create a bsice component similar described in https://arcticwolf.atlassian.net/wiki/spaces/PD/pages/4071326158/How+to+create+a+Backstage+catalog-info.yaml+file#Rollout-Instructions-for-SRE-Team
  tags:
    - recommended
spec:
  owner: backstage/techdocs-core
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in Core information
      properties:
        github_org:
          title: GitHub Organization
          type: string
          default: rktwlf
          enum:
            - rktwlf
            - rktwlf-actions
            - rktwlf-flags
            - root-secure
          enumNames:
            - 'Rtkwlf'
            - 'Rtkwlf Actions'
            - 'Rtkwlf Flags'
            - 'Root Secure'
        repo:
          title: Name
          type: string
          description: Name of the service/cell/repo
          pattern: '^([a-zA-Z][a-zA-Z0-9-]*)$' #TODO: find it is not work
        title:
          title: Title
          type: string
          description: Pretty name for the service/cell/repo
        description:
          title: Description
          type: string
          description: Repo description
          ui:widget: textarea
          ui:options:
            rows: 5
          ui:placeholder: |
            Put down your repository description here
        distributed:
          title: Distributed
          type: boolean
          description: Only true if the software is distributed to customers
          ui:widget: radio
        github_team:
          title: GitHub Team Owner
          type: string
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
        system:
          title: Architecture Component
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: System     
            defaultKind: System  
        
    - title: Fill in Plugin related information
      properties:
        jira_project_key: 
          title: Jira Project Key
          type: string
          description: Display issues from this Jira project

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - action: debug:log
      name: Debug Log Line
      input:
        message: repo_url https://github.com/${{ parameters.github_org }}/${{ parameters.repo }}
    - action: fetch:template
      id: fetch-template
      name: Fetch template
      input:
        url: https://github.com/backstage/demo/blob/master/catalog-info.yaml
        targetPath: ./target
        values:
          repo: ${{ parameters.repo }}
        # cookiecutterCompat: true
        templateFileExtension: yaml
    - action: publish:github:pull-request
      name: Create Github Pull Request
      input:
        repoUrl: 'github.com?repo=backstage-testing-2&owner=Chris-Testing-Company'
        branchName: add-catalog-info-file
        title: Add catalog-info.yaml to repo
        description: This PR is created by Backstage template entity. It is going to insert a catalog-info.yaml to repo for use in Backstage.
        draft: true
  # some outputs which are saved along with the job for use in the frontend
  output:
    links:
      - title: Template
        url: ${{ steps['fetch-template'] }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
